In [29]:
import numpy as np
import pylab as pl
import warnings
import math

from matplotlib import pyplot as plt
from scipy import linalg
from sklearn.datasets import load_digits
from sklearn.decomposition import TruncatedSVD
from sklearn.ensemble import RandomForestClassifier

Part1 

Придумайте матрицы, которые обладают следующими свойствами:

P.S. Во всех пунктах ответом должна быть ненулевая матрица размерности не менее 2!

a) диагональная, ортогональная, но не единичная(!):

In [40]:
A = np.array([[-1, 0],[0,-1]])

print("matrix A:\n", A)
print("A(At):\n", A @ np.transpose(A))
print("(At)A:\n", np.transpose(A) @ A)

matrix A:
 [[-1  0]
 [ 0 -1]]
A(At):
 [[1 0]
 [0 1]]
(At)A:
 [[1 0]
 [0 1]]


b) верхнетреугольная, ортогональная:

In [37]:
A = np.array([[-1, 0],
              [0, -1]])

print("matrix A:\n", A)
print("A(At):\n", A @ np.transpose(A))
print("(At)A:\n", np.transpose(A) @ A)

matrix A:
 [[-1  0]
 [ 0 -1]]
A(At):
 [[1 0]
 [0 1]]
(At)A:
 [[1 0]
 [0 1]]


c) нижнетреугольная, ортогональная:

In [38]:
A = np.array([[-1, 0],
              [0, -1]])

print("matrix A:\n", A)
print("A(At):\n", A @ np.transpose(A))
print("(At)A:\n", np.transpose(A) @ A)

matrix A:
 [[-1  0]
 [ 0 -1]]
A(At):
 [[1 0]
 [0 1]]
(At)A:
 [[1 0]
 [0 1]]


d) матрица, у которой определитель = 1, и все элементы не равны 0:

In [43]:
A = np.array([[2, 3],
              [1, 2]])

print("matrix A:\n", A)
print("det(A):\n", np.linalg.det(A))


matrix A:
 [[2 3]
 [1 2]]
det(A):
 1.0


Найдите собственные значения и собственные вектора матриц:

In [47]:
A = np.array([[2, 2],[1, 3]])

In [48]:
w, v = np.linalg.eig(A)

In [55]:
print("matrix A:\n",m)
for i in range(len(w)):
    print("eigenvalu " + str(w[i]), "eigenvector " + str(v[:,i]))

matrix A:
 [[2 2]
 [1 3]]
eigenvalu 1.0 eigenvector [-0.89442719  0.4472136 ]
eigenvalu 4.0 eigenvector [-0.70710678 -0.70710678]


Part 2    

Найдите спектральное разложение матрицы:
    

In [56]:
m = np.array([[1, 2],[2,3]])
print(m)

[[1 2]
 [2 3]]


In [63]:
a, U = linalg.eig(m)
print("Eigenvalues:")
print(np.array(a))
print("\nEigenvectors:")
print(U)

Eigenvalues:
[-0.23606798+0.j  4.23606798+0.j]

Eigenvectors:
[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


In [64]:
print(np.array(U.dot(np.diag(a)).dot(U.T)))

[[1.+0.j 2.+0.j]
 [2.+0.j 3.+0.j]]
